# Generated by Django 5.0.4 on 2024-06-06 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licensekey',
            name='key',
        ),
    ]
