# Generated by Django 5.0.4 on 2024-06-06 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_remove_licensekey_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensekey',
            name='key',
            field=models.TextField(default=''),
        ),
    ]
